### ISSUE TITLE
Slack test message fail

### ISSUE THREAD

**Issue by boskiv** [Graylog2/graylog-plugin-slack#41]
```
Unhandled rejection Error: cannot POST https://graylog.exness.io/api/alerts/callbacks/58bda789a7b11b0001f85900/test (500)
    at new t (https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:2770)
    at https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:4196
From previous event:
    at h.r.then (https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:20641)
    at e.value (https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:3714)
    at i (https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:1711)
    at s (https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:1782)
    at testAlert (https://graylog.exness.io/assets/plugin/org.graylog.plugins.pipelineprocess…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:151:26302)
    at n._onTestNotification (https://graylog.exness.io/assets/14.14.9f581fc7167d550338b4.js:1:5363)
    at Object.r.invokeGuardedCallback (https://graylog.exness.io/assets/vendor.js:29:11002)
    at i (https://graylog.exness.io/assets/vendor.js:33:26673)
    at Object.s [as executeDispatchesInOrder] (https://graylog.exness.io/assets/vendor.js:33:26920)
    at f (https://graylog.exness.io/assets/vendor.js:8:11906)
    at M (https://graylog.exness.io/assets/vendor.js:8:12032)
    at Array.forEach (native)
    at n (https://graylog.exness.io/assets/vendor.js:29:18772)
    at Object.processEventQueue (https://graylog.exness.io/assets/vendor.js:8:13329)
    at o (https://graylog.exness.io/assets/vendor.js:35:7775)
    at Object.handleTopLevel [as _handleTopLevel] (https://graylog.exness.io/assets/vendor.js:35:7880)
    at i (https://graylog.exness.io/assets/vendor.js:35:8329)
    at a (https://graylog.exness.io/assets/vendor.js:35:8143)
    at o.perform (https://graylog.exness.io/assets/vendor.js:8:25971)
    at Object.batchedUpdates (https://graylog.exness.io/assets/vendor.js:29:4842)
    at Object.a [as batchedUpdates] (https://graylog.exness.io/assets/vendor.js:7:19906)
    at dispatchEvent (https://graylog.exness.io/assets/vendor.js:35:9220)
```

```
Request URL:https://graylog.exness.io/api/alerts/callbacks/58bda789a7b11b0001f85900/test
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:192.168.168.59:443
```

But nothing in graylog log output.

I have run graylog thru docker.

**Comment by joschi** [comment]
@boskiv Which version of this plugin are you using?
Which version of Graylog are you using?
Are there any error messages in the logs of your Graylog container?

**Comment by boskiv** [comment]
No errors in container
graylog2/server:latest
plugin 2.4.0

**Comment by joschi** [comment]
@boskiv 
> No errors in container

There has to be some error message in the logs of your Graylog node. Depending on your configuration, this will be in some log file or on stdout of the container.

**Comment by boskiv** [comment]
@joschi I have checked files inside container, there is empty folder logs.
```
root@4b3123e1d5b6:/usr/share/graylog# cd log/
root@4b3123e1d5b6:/usr/share/graylog/log# ls -al
total 4
drwxr-xr-x 2 graylog graylog   10 Mar  2 13:01 .
drwxr-xr-x 7 graylog graylog 4096 Mar  6 12:21 ..
```
In stdout i see
```
graylog_1        | 2017-03-06 18:27:20,116 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input SyslogTCPInput{title=Syslog TCP, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=null} should be 1048576 but is 212992.
graylog_1        | 2017-03-06 18:27:20,119 INFO : org.graylog2.inputs.InputStateListener - Input [Syslog TCP/58bd58662ab79c0001c6f525] is now RUNNING
graylog_1        | 2017-03-06 18:27:20,127 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=Syslog UDP, type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=null} should be 262144 but is 212992.
graylog_1        | 2017-03-06 18:27:20,127 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=GELF UDP, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=null} should be 262144 but is 212992.
graylog_1        | 2017-03-06 18:27:20,129 INFO : org.graylog2.inputs.InputStateListener - Input [Syslog UDP/58bd587e2ab79c0001c6f541] is now RUNNING
graylog_1        | 2017-03-06 18:27:20,130 INFO : org.graylog2.inputs.InputStateListener - Input [GELF UDP/58bd8aa12ab79c000197598d] is now RUNNING
graylog_1        | 2017-03-06 18:27:23,927 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
graylog_1        | 2017-03-06 18:32:23,929 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
graylog_1        | 2017-03-06 18:32:23,931 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
graylog_1        | 2017-03-06 18:37:23,929 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
graylog_1        | 2017-03-06 18:37:23,931 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
graylog_1        | 2017-03-06 18:42:23,929 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
graylog_1        | 2017-03-06 18:42:23,931 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
graylog_1        | 2017-03-06 18:47:23,929 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
graylog_1        | 2017-03-06 18:47:23,931 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
graylog_1        | 2017-03-06 18:52:23,929 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
graylog_1        | 2017-03-06 18:52:23,931 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.


```

**Comment by boskiv** [comment]
Actually thats all gray log from start:
https://gist.github.com/boskiv/6c0b1ceadbd2b6a720652059d60ba3ab

May be I need to increase verbosity ?

**Comment by joschi** [comment]
@boskiv What software are you trying to use this plugin with and which version? I guess it's not Slack…

**Comment by boskiv** [comment]
@joschi I'm realy sorry, i have mistake in channel name to send in. I have stay with default one `#channel` cause webhook was created to specific one.
Now all works fine. Thank you for you help!

**Comment by joschi** [comment]
@boskiv No worries. Thanks for your feedback!
